- name: Install brew cask packages
  homebrew_cask:
    name: "{{ item.name }}"
  with_items:
    - { name: clipy }
    - { name: docker }
    - { name: drawio }
    - { name: dynalist }
    - { name: google-chrome }
    - { name: rectangle }
    - { name: typora }
