return {
	{ "L3MON4D3/LuaSnip" },
	{ "RRethy/vim-illuminate" },
	{ "andymass/vim-matchup" },
	{ "editorconfig/editorconfig-vim" },
	{ "folke/trouble.nvim" },
	{ "folke/which-key.nvim" },
	{ "hashivim/vim-terraform" },
	{ "hrsh7th/cmp-buffer" },
	{ "hrsh7th/cmp-cmdline" },
	{ "hrsh7th/cmp-nvim-lsp" },
	{ "hrsh7th/cmp-path" },
	{ "itchyny/lightline.vim" },
	{ "jay-babu/mason-null-ls.nvim" },
	{ "kyazdani42/nvim-web-devicons" },
	{
    "lewis6991/gitsigns.nvim",
    config = true,
  },
	  "lukas-reineke/indent-blankline.nvim",
	  main = "ibl",
	  ---@module "ibl"
	  ---@type ibl.config
	  opts = {
	    indent = { char = '¦' }
	  },
	},
	{ "machakann/vim-highlightedyank" },
	{ "mbbill/undotree" },
	{ "mg979/vim-visual-multi" },
	{ "nvim-lua/plenary.nvim" },
	{ "nvim-telescope/telescope-file-browser.nvim" },
	{ "nvim-tree/nvim-web-devicons" },
	{ "onsails/lspkind-nvim" },
	{ "psliwka/vim-smoothie" },
	{ "rebelot/kanagawa.nvim" },
	{ "statianzo/vim-jade" },
	{ "thinca/vim-quickrun" },
	{ "tpope/vim-abolish" },
	{ "tpope/vim-fugitive" },
	{ "williamboman/mason-lspconfig.nvim" },
	{ "williamboman/mason.nvim" },
	{ "windwp/nvim-ts-autotag" },
	{ "zbirenbaum/copilot-cmp" },
	{ "zbirenbaum/copilot.lua" },
}
