---
- name: Install for neovim general plugins
  git:
    repo: "https://github.com/{{ item.namespace }}/{{ item.name }}.git"
    dest: "$HOME/.local/share/nvim/site/pack/{{ item.namespace }}/start/{{ item.name }}"
    depth: 1
    version: "{{ item.version | default('HEAD') }}"
  with_items:
    - { namespace: RRethy, name: vim-illuminate }
    - { namespace: Yggdroot, name: indentLine }
    - { namespace: airblade, name: vim-gitgutter }
    - { namespace: cocopon, name: vaffle.vim }
    - { namespace: cohama, name: lexima.vim }
    - { namespace: dense-analysis, name: ale }
    - { namespace: easymotion, name: vim-easymotion }
    - { namespace: editorconfig, name: editorconfig-vim }
    - { namespace: elzr, name: vim-json }
    - { namespace: hashivim, name: vim-terraform }
    - { namespace: itchyny, name: lightline.vim }
    - { namespace: junegunn, name: fzf.vim }
    - { namespace: kevinhwang91, name: nvim-hlslens }
    - { namespace: machakann, name: vim-highlightedyank }
    - { namespace: machakann, name: vim-sandwich }
    - { namespace: mbbill, name: undotree }
    - { namespace: mg979, name: vim-visual-multi }
    - { namespace: petertriho, name: nvim-scrollbar }
    - { namespace: prabirshrestha, name: asyncomplete-buffer.vim }
    - { namespace: prabirshrestha, name: asyncomplete-lsp.vim }
    - { namespace: prabirshrestha, name: asyncomplete.vim }
    - { namespace: ryanoasis, name: vim-devicons }
    - { namespace: statianzo, name: vim-jade }
    - { namespace: thinca, name: vim-quickrun }
    - { namespace: thinca, name: vim-submode }
    - { namespace: tpope, name: vim-abolish }
    - { namespace: tpope, name: vim-fugitive }
    - { namespace: w0ng, name: vim-hybrid }

- name: Install for neovim special plugins
  git:
    repo: "https://github.com/{{ item.namespace }}/{{ item.name }}.git"
    dest: "$HOME/.local/share/nvim/site/pack/{{ item.namespace }}/opt/{{ item.name }}"
    depth: 1
    version: "{{ item.version | default('HEAD') }}"
  with_items:
    - { namespace: leafgarland, name: typescript-vim }
    - { namespace: maxmellon, name: vim-jsx-pretty }

- name: Install oh-my-zsh
  git:
    repo: "https://github.com/ohmyzsh/ohmyzsh.git"
    dest: "$HOME/.oh-my-zsh"
    depth: 1

- name: Install oh-my-zsh plugin
  git:
    repo: "https://github.com/{{ item.namespace }}/{{ item.name }}.git"
    dest: "$HOME/.oh-my-zsh/custom/plugins/{{ item.name }}"
    depth: 1
    version: "{{ item.version | default('HEAD') }}"
  with_items:
    - { namespace: zsh-users, name: zsh-syntax-highlighting }
    - { namespace: zsh-users, name: zsh-autosuggestions }

- name: Link custom plugin
  file:
    src: $HOME/.zsh/ws
    dest: $HOME/.oh-my-zsh/custom/plugins/ws
    state: link
