---
- name: Install brew packages
  homebrew:
    name: "{{ item.name }}"
  with_items:
    - { name: ag }
    - { name: bat }
    - { name: direnv }
    - { name: ffmpeg }
    - { name: fzf }
    - { name: ghc }
    - { name: git } # Use homebrew based git
    - { name: gnu-sed }
    - { name: grex }
    - { name: hexyl }
    - { name: htop }
    - { name: httpie }
    - { name: imagemagick }
    - { name: jq }
    - { name: jump }
    - { name: lsd }
    - { name: neofetch }
    - { name: neovim }
    - { name: nkf }
    - { name: pandoc }
    - { name: pict }
    - { name: poppler }
    - { name: postgresql }
    - { name: qrencode }
    - { name: tmux }
    - { name: w3m }
    - { name: yarn }

- name: Tap lazygit
  homebrew_tap:
    name: "{{ item.name }}"
  with_items:
    - { name: "jesseduffield/lazygit" }
- name: Install lazygit
  homebrew:
    name: "{{ item.name }}"
  with_items:
    - { name: "jesseduffield/lazygit/lazygit" }

- name: Install pass
  homebrew:
    name: "{{ item.name }}"
  with_items:
    - { name: pass }
    - { name: pass-otp }
    - { name: pinentry-mac }
- name: Install safari extension
  homebrew_cask:
    name: adur1990/tap/passformacos
- name: Change permission
  shell: chmod 700 $HOME/.gnupg
- name: Create conf
  copy:
    content: ''
    dest: $HOME/.gnupg/gpg-agent.conf
    force: no
- name: Get path of pinentry-mac
  shell: which pinentry-mac
  register: pinentry_mac_path
- name: Change config
  lineinfile:
    path:  $HOME/.gnupg/gpg-agent.conf
    line: 'pinentry-program {{ pinentry_mac_path.stdout }}'

- name: Set up lsd
  blockinfile:
    path: $HOME/.zprofile
    block: |
      alias ls='lsd -l'
      alias tree='lsd --tree'
    marker: "# {mark} ANSIBLE MANAGED BLOCK lsd"

- name: Set up bat
  blockinfile:
    path: $HOME/.zprofile
    block: |
      alias cat='bat --paging=never'
      export MANPAGER='`col -bx | bat -l man -p`'
    marker: "# {mark} ANSIBLE MANAGED BLOCK bat"
