---
- name: Install for neovim general plugins
  git:
    repo: "https://github.com/{{ item.namespace }}/{{ item.name }}.git"
    dest: "$HOME/.local/share/nvim/site/pack/{{ item.namespace }}/start/{{ item.name }}"
    depth: 1
    version: "{{ item.version | default('HEAD') }}"
  with_items:
    - { namespace: RRethy, name: vim-illuminate }
    - { namespace: Yggdroot, name: indentLine }
    - { namespace: airblade, name: vim-gitgutter }
    - { namespace: cohama, name: lexima.vim }
    - { namespace: dense-analysis, name: ale }
    - { namespace: easymotion, name: vim-easymotion }
    - { namespace: editorconfig, name: editorconfig-vim }
    - { namespace: elzr, name: vim-json }
    - { namespace: hashivim, name: vim-terraform }
    - { namespace: itchyny, name: lightline.vim }
    - { namespace: kevinhwang91, name: nvim-hlslens }
    - { namespace: machakann, name: vim-highlightedyank }
    - { namespace: machakann, name: vim-sandwich }
    - { namespace: mbbill, name: undotree }
    - { namespace: mg979, name: vim-visual-multi }
    - { namespace: psliwka, name: vim-smoothie }
    - { namespace: statianzo, name: vim-jade }
    - { namespace: thinca, name: vim-quickrun }
    - { namespace: thinca, name: vim-submode }
    - { namespace: tpope, name: vim-abolish }
    - { namespace: tpope, name: vim-fugitive }
    - { namespace: w0ng, name: vim-hybrid }

- name: Install for neovim special plugins
  git:
    repo: "https://github.com/{{ item.namespace }}/{{ item.name }}.git"
    dest: "$HOME/.local/share/nvim/site/pack/{{ item.namespace }}/opt/{{ item.name }}"
    depth: 1
    version: "{{ item.version | default('HEAD') }}"
  with_items:
    - { namespace: leafgarland, name: typescript-vim }
    - { namespace: maxmellon, name: vim-jsx-pretty }

- name: Install vaffle.vim
  block:
    - name: Install neovim plugins for vaffle.vim
      git:
        repo: "https://github.com/{{ item.namespace }}/{{ item.name }}.git"
        dest: "$HOME/.local/share/nvim/site/pack/{{ item.namespace }}/start/{{ item.name }}"
        depth: 1
        version: "{{ item.version | default('HEAD') }}"
      with_items:
        - { namespace: cocopon, name: vaffle.vim }
        - { namespace: ryanoasis, name: vim-devicons }

- name: Install lightline.vim
  block:
    - name: Install neovim plugins for lightline.vim
      git:
        repo: "https://github.com/{{ item.namespace }}/{{ item.name }}.git"
        dest: "$HOME/.local/share/nvim/site/pack/{{ item.namespace }}/start/{{ item.name }}"
        depth: 1
        version: "{{ item.version | default('HEAD') }}"
      with_items:
        - { namespace: itchyny, name: lightline.vim }
        - { namespace: ryanoasis, name: vim-devicons }

- name: Install telescope.nvim
  block:
    - name: Install brew packages for telescope.nvim
      homebrew:
        name: ripgrep
    - name: Install neovim plugins for telescope.nvim
      git:
        repo: "https://github.com/{{ item.namespace }}/{{ item.name }}.git"
        dest: "$HOME/.local/share/nvim/site/pack/{{ item.namespace }}/start/{{ item.name }}"
        depth: 1
        version: "{{ item.version | default('HEAD') }}"
      with_items:
        - { namespace: kyazdani42, name: nvim-web-devicons }
        - { namespace: nvim-lua, name: plenary.nvim  }
        - { namespace: nvim-telescope, name: telescope.nvim }

- name: Install neovim nvim-lspconfig
  block:
    - name: Install neovim plugins for nvim-lspconfig
      git:
        repo: "https://github.com/{{ item.namespace }}/{{ item.name }}.git"
        dest: "$HOME/.local/share/nvim/site/pack/{{ item.namespace }}/start/{{ item.name }}"
        depth: 1
        version: "{{ item.version | default('HEAD') }}"
      with_items:
        - { namespace: neovim, name: nvim-lspconfig }

- name: Install nvim-cmp
  block:
    - name: Install neovim plugins for nvim-cmp
      git:
        repo: "https://github.com/{{ item.namespace }}/{{ item.name }}.git"
        dest: "$HOME/.local/share/nvim/site/pack/{{ item.namespace }}/start/{{ item.name }}"
        depth: 1
        version: "{{ item.version | default('HEAD') }}"
      with_items:
        - { namespace: L3MON4D3, name: LuaSnip }
        - { namespace: hrsh7th, name: cmp-buffer }
        - { namespace: hrsh7th, name: cmp-cmdline }
        - { namespace: hrsh7th, name: cmp-nvim-lsp }
        - { namespace: hrsh7th, name: cmp-path }
        - { namespace: hrsh7th, name: nvim-cmp }
        - { namespace: onsails, name: lspkind-nvim }

# After installation, start Neovim and invoke :Copilot setup.
- name: Enable copilot
  block:
    - name: Install copilot neovim plugins
      git:
        repo: "https://github.com/{{ item.namespace }}/{{ item.name }}.git"
        dest: "$HOME/.local/share/nvim/site/pack/{{ item.namespace }}/start/{{ item.name }}"
        depth: 1
        version: "{{ item.version | default('HEAD') }}"
      with_items:
        - { namespace: github, name: copilot.vim }
