---
# Install latest
- file: path=$HOME/.nodebrew/src state=directory
- name: Detect if nodebrew is installed
  stat: path=$HOME/.nodebrew/current/bin/nodebrew
  register: nodebrew_bin
- name: Install nodebrew
  homebrew:
    name: nodebrew
- name: Detect if npm is installed
  stat: path=$HOME/.nodebrew/current/bin/npm
  register: npm_bin
- name: Install NodeJS
  shell: nodebrew install latest
  when: not npm_bin.stat.exists
- name: Use latest NodeJS
  shell: nodebrew use latest
  when: not npm_bin.stat.exists
