---
- name: init
  hosts: localhost
  connection: local
  gather_facts: yes
  roles:
    - role: init
      tags: init

- name: cui
  hosts: localhost
  connection: local
  gather_facts: yes
  roles:
    - role: cui
      tags: cui

- name: gui
  hosts: localhost
  connection: local
  gather_facts: yes
  roles:
    - role: gui
      tags: gui

- name: appstore
  hosts: localhost
  connection: local
  gather_facts: yes
  roles:
    - role: appstore
      tags: appstore

- name: os
  hosts: localhost
  connection: local
  gather_facts: yes
  handlers:
    - name: "Restart Dock"
      shell: "killall Dock"
    - name: "Restart Finder"
      shell: "killall Finder"
  roles:
    - role: os
      tags: os
