---
- name: Install rbenv
  homebrew:
    name: rbenv

- name: Init rbenv
  shell: rbenv init -

- name: Detect if ruby is installed
  stat: path=$HOME/.rbenv/shims/ruby
  register: ruby_bin

- name: Get latest ruby version
  shell: rbenv install --list-all | grep -v - | tail -1
  register: ruby_version
  when: not ruby_bin.stat.exists

- name: Install latest ruby
  shell: zsh -lc "rbenv install -s {{ ruby_version.stdout }}"
  when: not ruby_bin.stat.exists

- name: Use latest ruby
  shell: rbenv global {{ ruby_version.stdout }}
  when: not ruby_bin.stat.exists

- name: Update gem
  shell: gem update --user-install
  when: not ruby_bin.stat.exists
