---
- name: Use homebrew based git
  homebrew:
    name: "git"

- name: Set git global configurations
  block:
    - git_config:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        scope: global
      with_items:
        - { name: "core.editor", value: "nvim" }
        - { name: "core.excludesfile", value: "~/.gitignore" }
        - { name: "core.quotepath", value: "false" }
        - { name: "pull.rebase", value: "true" }
        - { name: "pager.branch", value: "false" }
        - { name: "pager.stash", value: "false" }
        - { name: "user.email", value: "rikuson@users.noreply.github.com" }
        - { name: "user.name", value: "Riku Takeuchi" }
        - { name: "merge.tool", value: "nvimdiff" }
        - { name: "init.defaultBranch", value: "main" }
    - template:
        src: roles/cui/templates/.gitignore
        dest: $HOME
