---
- name: Tap brew repositories
  community.general.homebrew_tap:
    name:
      - datadog-labs/pack

- name: Install brew packages
  community.general.homebrew:
    name:
      - bat
      - binaryen
      - cmake
      - coreutils
      - direnv
      - ffmpeg
      - font-fira-code-nerd-font
      - fzf
      - gh
      - ghc
      - git # Use homebrew based git
      - gnu-sed
      - grex
      - hexyl
      - htop
      - imagemagick
      - jinja2-cli
      - jq
      - lsd
      - mas
      - neovim
      - nkf
      - pandoc
      - pict
      - pkg-config
      - poppler
      - datadog-labs/pack/pup
      - qrencode
      - tmux
      - tree-sitter-cli
      - yarn
      - yq
      - yt-dlp

- name: Install brew cask packages
  community.general.homebrew_cask:
    name:
      - httpie

- name: Create .tmux.conf
  template:
    src: roles/cui/templates/.tmux.conf
    dest: $HOME

- name: Set up lsd
  blockinfile:
    path: $HOME/.zprofile
    block: |
      alias ls='lsd -l'
      alias tree='lsd --tree'
    marker: "# {mark} ANSIBLE MANAGED BLOCK lsd"

- name: Set up bat
  blockinfile:
    path: $HOME/.zprofile
    block: |
      alias cat='bat --paging=never'
      export MANPAGER='`col -bx | bat -l man -p`'
    marker: "# {mark} ANSIBLE MANAGED BLOCK bat"

- name: Set up nvim
  blockinfile:
    path: $HOME/.zprofile
    block: |
      alias vim='nvim'
    marker: "# {mark} ANSIBLE MANAGED BLOCK nvim"
