---
- name: Create .zprofile
  file:
    path: $HOME/.zprofile
    state: touch
- name: Create .zshrc
  template:
    src: roles/cui/templates/.zshrc
    dest: $HOME

- import_tasks: homebrew.yml
- import_tasks: asdf.yml
- import_tasks: ohmyzsh.yml
- import_tasks: neovim.yml
- import_tasks: git.yml
