---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - $HOME/.config/lazygit
    - $HOME/.config/nvim/lua/config
    - $HOME/.config/nvim/lua/plugins

- name: Copy lazygit config
  template:
    src: roles/cui/templates/.config/lazygit/config.yml
    dest: $HOME/.config/lazygit/config.yml

- name: Copy plugin manager config
  template:
    src: "{{ item }}"
    dest: "$HOME/.config/nvim/lua/config/{{ item | basename }}"
  loop: "{{ lookup('fileglob', 'roles/cui/templates/.config/nvim/lua/config/*.lua', wantlist=True) }}"

- name: Copy plugin settings
  template:
    src: "{{ item }}"
    dest: "$HOME/.config/nvim/lua/plugins/{{ item | basename }}"
  loop: "{{ lookup('fileglob', 'roles/cui/templates/.config/nvim/lua/plugins/*.lua', wantlist=True) }}"

- name: Install dependencies of toggleterm.nvim
  community.general.homebrew:
    name:
      - lazygit
      - lazydocker
      - ripgrep

- name: Create config file
  template:
    src: roles/cui/templates/.config/nvim/init.lua
    dest: $HOME/.config/nvim/init.lua

- name: Create plugin lock file
  file:
    src: "{{ playbook_dir }}/roles/cui/templates/.config/nvim/lazy-lock.json"
    dest: $HOME/.config/nvim/lazy-lock.json
    state: link
    force: true
