---
- name: Create directories
  block:
    - file:
        path: $HOME/.config/lazygit
        state: directory
        mode: "0755"

- name: Copy lazygit config
  template:
    src: roles/cui/templates/.config/lazygit/config.yml
    dest: $HOME/.config/lazygit/config.yml

- name: Copy plugin manager config
  template:
    src: "{{ item }}"
    dest: "$HOME/.config/nvim/lua/config/{{ item | basename }}"
  with_fileglob:
    - roles/cui/templates/.config/nvim/lua/config/*.lua

- name: Copy plugin settings
  template:
    src: "{{ item }}"
    dest: "$HOME/.config/nvim/lua/plugins/{{ item | basename }}"
  with_fileglob:
    - roles/cui/templates/.config/nvim/lua/plugins/*.lua

- name: Install dependencies of toggleterm.nvim
  homebrew:
    name: "{{ item.name }}"
  with_items:
    - { name: lazygit }
    - { name: lazydocker }
    - { name: ripgrep }

- name: Create config file
  template:
    src: roles/cui/templates/.config/nvim/init.lua
    dest: $HOME/.config/nvim/init.lua

- name: Create plugin lock file
  file:
    src: "{{ playbook_dir }}/roles/cui/templates/.config/nvim/lazy-lock.json"
    dest: $HOME/.config/nvim/lazy-lock.json
    state: link
    force: true
