- name: Tap brew packages
  homebrew_tap:
    name: "homebrew/cask-fonts"

- name: Install brew cask packages
  homebrew_cask:
    name: "{{ item.name }}"
  with_items:
    - { name: clipy }
    - { name: docker }
    - { name: drawio }
    - { name: dynalist }
    - { name: font-fira-code-nerd-font }
    - { name: google-chrome }
    - { name: typora }
